language: go

services:
  - docker

before_script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run --enable-all
  - docker build -t $TRAVIS_REPO_SLUG .
  # - bash docker-push.sh
