language: go

services:
  - docker

before_script:
  - go get -u github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - golangci-lint run --enable-all
  # - bash docker-push.sh

deploy:
  provider: script
  script: bash docker-push.sh
